version: '3.3'

services:
    api-server:
        build: ./api-server/
        restart: always
        ports:
            - 443:443
        volumes:
            - ./api-server:/usr/src/app
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
    postgres:
        image: ./postgres/
        restart: always
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432